server:
  port: 8889

minio:
  endpoint: http://192.168.52.63:9000/
  accesskey: minio
  secretKey: ABCDabcd1234@

kafka:
  zookeeper: zookeeper.kafka.com:1081
  #broker: 192.168.20.154:30861
  broker: k8s-master:18001

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB